//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDBGS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edbgsEntities : DbContext
    {
        public edbgsEntities()
            : base("name=edbgsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<economy> economies { get; set; }
        public virtual DbSet<edfaction> edfactions { get; set; }
        public virtual DbSet<edfactionhist> edfactionhists { get; set; }
        public virtual DbSet<edpendingstate> edpendingstates { get; set; }
        public virtual DbSet<edstation> edstations { get; set; }
        public virtual DbSet<edsystem> edsystems { get; set; }
        public virtual DbSet<edsystemhist> edsystemhists { get; set; }
        public virtual DbSet<govtype> govtypes { get; set; }
        public virtual DbSet<power> powers { get; set; }
        public virtual DbSet<powerstate> powerstates { get; set; }
        public virtual DbSet<reserve> reserves { get; set; }
        public virtual DbSet<security> securities { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<superpower> superpowers { get; set; }
    }
}
