//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDBGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class edfaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public edfaction()
        {
            this.edstations = new HashSet<edstation>();
            this.edfactionhists = new HashSet<edfactionhist>();
            this.edsystemhists = new HashSet<edsystemhist>();
        }
    
        public long edfactionId { get; set; }
        public string Name { get; set; }
        public long HomeSystem { get; set; }
        public bool IsPlayerFaction { get; set; }
        public int govtype { get; set; }
        public int allegiance { get; set; }
        public Nullable<long> EDDNId { get; set; }
    
        public virtual superpower superpower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edstation> edstations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edfactionhist> edfactionhists { get; set; }
        public virtual govtype govtype1 { get; set; }
        public virtual edsystem edsystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edsystemhist> edsystemhists { get; set; }
    }
}
