//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDBGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class edfactionhist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public edfactionhist()
        {
            this.edpendingstates = new HashSet<edpendingstate>();
        }
    
        public long edfactionhistId { get; set; }
        public Nullable<long> edfactionid { get; set; }
        public Nullable<long> edsystemid { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<float> influence { get; set; }
    
        public virtual edfaction edfaction { get; set; }
        public virtual state state { get; set; }
        public virtual edsystem edsystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edpendingstate> edpendingstates { get; set; }
    }
}
