//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDBGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class edpendingstate
    {
        public int edpendingstatesid { get; set; }
        public Nullable<long> edfactionhistid { get; set; }
        public Nullable<int> trend { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> EDDNId { get; set; }
    
        public virtual edfactionhist edfactionhist { get; set; }
        public virtual state state { get; set; }
    }
}
