//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDBGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class edsystemhist
    {
        public long edsystemhistid { get; set; }
        public long edsystemid { get; set; }
        public System.DateTime timestamp { get; set; }
        public long controlingfactionid { get; set; }
        public int economyid { get; set; }
        public int powerid { get; set; }
        public int powerstateid { get; set; }
        public int securityid { get; set; }
        public int EDDNId { get; set; }
    
        public virtual economy economy { get; set; }
        public virtual edfaction edfaction { get; set; }
        public virtual edsystem edsystem { get; set; }
        public virtual power power { get; set; }
        public virtual powerstate powerstate { get; set; }
        public virtual security security { get; set; }
    }
}
